ls_reliability:
  title: ナイトと忍者のＬＳ信頼度は違いすぎた
  body: |-
    やはり忍者よりナイトの方が頼りにされていた
    キングベヒーもスとの戦いでおれは集合時間に遅れてしまったんだがちょうどわきはじめたみたいでなんとか耐えているみたいだった
    おれはジュノにいたので急いだ
    ところがアワレにも忍者がくずれそうになっているっぽいのがＬＳ会話で叫んでいた
    どうやら忍者がたよりないらしく「はやくきて～はやくきて～」と泣き叫んでいるＬＳメンバーのために俺はとんずらを使って普通ならまだ付かない時間できょうきょ参戦すると
    「もうついたのか！」「はやい！」「きた！盾きた！」「メイン盾きた！」「これで勝つる！」と大歓迎状態だった
    忍者はアワレにも盾の役目を果たせず死んでいた
    近くですばやくフラッシュを使い盾をした
    忍者から裏テルで「勝ったと思うなよ・・・」ときたがＬＳメンバーがどっちの見方だかは一瞬でわからないみたいだった
    「もう勝負ついてるから」というと黙ったので戦士サポ忍の後ろに回り不意だまスフィストを打つと何回かしてたらキングベヒんもスは倒された
    「ナイトのおかげだ」「助かった、終わったと思ったよ」と忍者を行き帰らせるのも忘れてメンバーがおれのまわりに集まってきた忘れられてる忍者がかわいそうだった
    普通なら裏テルのことで無視する人がぜいいんだろうがおれは無視できなかった
    みんなとよｒこびほめられたかったのでレイズを唱えてやったらそうとう自分の裏テルが恥ずかしかったのかＨＰに帰って行った
aeris:
  title: エアリスを使うやつは心が醜い
  body: |-
    俺はＦＦ通してやってる自他共に認める熟練者なのだが先日ゲームに無関心だった姉が急にＦＦ７を貸してくれと言って来た
    俺はどうせＦＦ７のキャラ目当てだなと踏んでいたんだがどうやらその通りみたいで、腐女子仲間に何を思ったかＦＦ７ＡＣを借りて見たらしい
    そういうの嫌いだから俺は｢いや、そういうのでやって欲しくないから｣と言ったら何か必死な顔して出て行った
    そしたらムキになってなんか中古で買ってきたみたいで１人でむくむくとやっていた
    しばらくは俺も放置していたんだが何かたまたまのぞいて見るとクラウド・レッドⅩⅢ・エアリスとか貧弱ＰＴでもう見てられなかったから
    ｢何でエアリス使ってんの？ティファのが強いしエアリス死ぬよ？｣ってやさしく忠告してやったらなんか顔真っ赤にしてコッチにらんで来た
    俺は｢何？｣って言ったらすごい形相で｢クラエアがデフォだしティファとかブサイクで醜い女入れたくない｣とか怒鳴ってきた
    そこまで俺はティファは好きではなくむしろ強キャラでモンクタイプが好きだったから言っただけなのになんかカチンときので
    ｢は？エアリスってリミットゴミでしょ？それに強制離脱するから育てても無駄｣と正論言ってやったら今にも俺を殺してきそうな殺意を向けてきた
    実際俺は不良界でも結構有名でケンカとかでもたいしてビビる事はまず無かったが生まれて初めてほんの少しビビった
    そしたらなんか｢あたしの勝手じゃん！クラエア馬鹿にする気？そうならあんたもう死ね！｣とか実の弟の俺にリアルで殺意向けてヤバかった
shameless_ky:
  title: 恥知らずなカイ使いがいた！
  body: |-
    俺はソルを使い手なんだが相手が残念な事にカイを使ってきたので「お前それで良いのか？」と言うと「何いきなり話かけて来てるわけ？」と言われた。
    俺の弟がカイの熟練者なのだがおれはいつも勝つから相手が気の毒になったので聞いただけなんだがむかついたので「お前ﾊｲｽﾗでﾎﾞｺるわ・・」と
    言って開始直後に力を溜めて前ﾊｲｽﾗしたら多分リアルでビビったんだろうな、、ｶﾞｰﾄﾞ固めてたからｷｬﾝｾﾙしてｶｶッっとﾀﾞｯｼｭしながらﾊｲｽﾗしたらかなり青ざめてた
    おれは一気に空中にとんだんだけどカイが硬直してておれの動きを見失ったのか動いてなかったからｺﾏﾝﾄﾞ投げでｶﾞｰﾄﾞを崩した上についげきのグランドヴァイパでさらにﾀﾞﾒｰｼﾞは加速した。
    わざと距離をとり「俺はこのままﾀｲﾑｱｯﾌﾟでもいいんだが？」というとようやく必死な顔してなんか剣のはしっこから氷出してきた。
    おれはしゃがみダストで回避、これは一歩間違えるとｶｳﾝﾀｰで大ﾀﾞﾒｰｼﾞを受ける隠し技なので後ろのギャラリーが拍手し出した。
    俺は「うるさい、気が散る。一瞬の油断が命取り」というとｷﾞｬﾗﾘｰは黙った
    カイは必死にやってくるが、時既に時間切れ、下段ｶﾞｰﾄﾞを固めた俺にｽｷはなかった
    たまに来る下段ｶﾞｰﾄﾞでは防げない攻撃もキックで撃退、終わる頃にはズタズタにされた金髪の雑魚がいた
    「いつでもﾊｲｽﾗでトドメは刺せた、あの時氷だそうとしたときにも実はズタズタに出来た、」とかいった
    そしたら「いや今のハメでしょ？俺のシマじゃ今のノーカンだから」とかいったので俺がヒト睨みするとまた俺から視線を外した、２戦目は俺のﾊｲｽﾗを先読みしてたみたいでいきなりバックステッポで回避された
    「ほう、経験が生きたな」と少し誉めるとｼﾞｭｰｽをおごってくれると言う約束をしたので空中でダストを当てて一気にかけよりダストと足払いの二択を迫り
    ５回くらい足払いしたら死を感じたのかｶﾞｰﾄﾞしようとしたので近づいてﾊｲｽﾗ投げをお見舞いしてやった、絶望でダウンしているところにｷﾞﾛﾁﾝのﾊｲｽﾗがダブルで入れた。
    「今のがリアルでなくて良かったな、リアルだったらお前はもう死んでるぞ」というと想像して圧倒されたのか動きが鈍くなったのでガンフレで動きをコントロールしさらに時間までコントロールしていることにも気付かせずにﾀｲﾑｱｯﾌﾟさせた。
    そしたら「まただよ（笑）」とか負けたくせに言いワケ言ってたから「限られたルールの中で勝利条件を満たしただけ」といったら顔真っ赤にして３戦目はけっこう攻撃的だったけど挑発に軽々と乗ってくる馬鹿には確実な死が待っていた。
    ハイスラの恐怖が完全に摺り込まれている為思うように近づけないでいるようで空中来たらキックでけん制し飛び込んできたら前ハイスラでいつの間にかｶﾞｰﾄﾞｹﾞｰｼﾞは光っていたから「グランドヴァイパでトドメさすよ」と言うとカイは必死にｶﾞｰﾄﾞしたから
    狙い通り３段目くらいをロマキャンすると予想通り青ざめてｶﾞｰﾄﾞしてたから投げで強打したのちハイスラでトドメ。
    あとはﾀｲﾑｱｯﾌﾟまで粘った。俺の下段ｶﾞｰﾄﾞは固く、隙を見せなかった。カイも下段ｶﾞｰﾄﾞできない攻撃してきたけど反撃もここまで。残念ながら前半の遅れを取り戻す事が出来なかった。
    その後ボコボコにして圧勝してやった
    変な空間になったので俺はミステリーを残す為勝ちの画面になったと同時に家に帰ったが多分不良界で伝説になってる
dirty_ninja:
  title: 汚いなさすが忍者きたない
  body: |-
    これ立てたの絶対忍者だろ･･汚いなさすが忍者きたない
    俺はこれで忍者きらいになったなあもりにもひきょう過ぎるでしょう？
    俺は中立の立場で見てきたけどやはりナイト中心で行った方が良い事が判明した
    忍はウソついてまでＰＴの盾役を確保したいらしいがナイトに相手されてない事くらいいい加減気づけよ
    ナイトは忍者よりも高みにいるからお前らのイタズラにも笑顔だったがいい加減にしろよ
golden_iron:
  title: 黄金の鉄の塊
  body: |-
    お前らは馬鹿すぐる
    ナイトが強いのは当然に決まっている
    黄金の鉄の塊で出来ているナイトが皮装備のｼﾞｮﾌﾞに遅れをとるはずは無い
    確実にナイトはエクスカリバを手に入れたら高確率で一番最強になる
golden_iron_res:
  title: 黄金の鉄の塊_res
  body: |-
    俺はただの通りすがりの古代からいるナイト
    最近フラッシュと言う魔法で空蝉忍者と同等の回避能力を手に入れただけ
    しかも回避能力はどうとうでありながら当たってもアダマンインゴ並の硬さを誇ってるから最強に近いと言える
    攻撃もエクスカリバ手に入れれば敵はそのまま骨になる
mad_and_die:
  title: 頭がおかしくなって死ぬ
  body: |-
    もうここまででも十分にグラットンの勝ちは圧勝に決まったのだが
    さらに攻撃は続く
    次は見た目に注目するのだが
    セイブはただのひょろっとした弱そうな形
    あれで斬られてもあまり痛くはない
    しかしグラットンは尖った部分が多くあの部分でさらに敵に致命的な致命傷を与えられる
    色も黒っぽいのでダークパワーが宿ってそうで強い
    ちなみにダークパワーっぽいのはナイトが持つと
    光と闇が両方そなわり最強に見える
    暗黒が持つと逆に頭がおかしくなって死ぬ
lightning_left:
  title: 雷属性の左
  body: |-
    俺はしがないエリート会社員なんだが先週同僚のもてない♂がなれなれしくも話しかけてきてウザかったが
    まぁ聞いてやるかと思って聞いてやったら何やら合コンをセッテングしてほしい様子で面倒だったんだがやってやった
    俺の行きつけの子じゃれたＢＡＲに行ったんだが暫らく皆で良い感じで話してたらよそで言い争いがはじまった
    せっかくのふいんきが台無しになって俺が主導権にぎって進めてたが仕方ないと思い店換えをする事にしたが
    何やらリアルファイトに発展したようで店員もビビりまくっているようだった。誰かが｢通報・・｣と言ったので俺らはほっといて出るつもりだったんだけど
    いきなり飛んできたビールが俺目当てのいけてる♀に直撃→俺の怒り発動の連鎖で俺は現場に躍り出ると
    いかついオッサンが｢何だガキ？ひっこんでろ！｣と言って来たので｢おい・・ツレにビールかかったんだわ・・クリ代払ってもらおうか？｣
    と怒りをこめて言い放つと｢言っとくが俺は空手二段だ。そこに転がってる奴みたくなりたくなかったらうせろ｣と息巻いてきたので
    スキだらけだったので雷属性の左をジョーにヒットさせてやって｢口で語るひまがあるなら手を出すべきだったな｣と言ってＫＯした
    自称空手二段は何がおこったのか分からずブザマにもプルプル足震えて倒れた
    おれはソイツからクリ代と飲み代を取りすかさず店に払って♀達を送って帰った。ちなみに警察はだいぶ後に来たらしい
    その後は一緒にいた♀達にどうやらほれられてしまい対応に困ったんだが何しに行ったか分からなかった同僚♂がアワレだった
    嫌味かは知らないが｢良いなケンカ強くて頭が切れる人は・・｣とかかわいそうな事言ってきたが俺は｢男ならアレくらいチョロイ事｣
    と大人の対応をしてやるとよほど悔しかったのか今さらながらスポーツジムで体を鍛えだしていた
rage:
  title: 俺の怒りが有頂天
  body: |-
    お前らは一級廃人のおれの足元にも及ばない貧弱一般人
    その一般人どもが一級廃人のおれに対してナメタ言葉を使うことでおれの怒りが有頂天になった
    この怒りはしばらくおさまる事を知らない
instinctive:
  title: 本能的に長寿タイプ
  body: |-
    また調子に乗り出してきたばかが沸いたな
    俺は別に強さをアッピルなどしてはいない
    俺を強いと感じてしまってるやつは本能的に長寿タイプ
    自分がリアルモンクとかいっていきがってる馬鹿がいるけどリアルモンクが一人だけだと思うなよ
    俺は防御もかなりかたい
upper_knight:
  title: 上げたくてあげるんじゃない上がってしまう者がナイト
  body: |-
    ナイトはスキルも性格もいいのでＬＳメンバーからは良くたよりにされる
    だがたよりにされたいからナイトを上げてもダメだと言う事が最近わかった
    ナイトを上げるのは真にナイトの人だからナイトを上げたくてあげるんじゃない上がってしまう者がナイト
    忍者はざんねんがはっきりいってスキルはつかわないし性格も裏テルとかイマイチだから信頼されにくい
opposition:
  title: どちかというと大反対
  body: |-
    ナイトに弱体とかお前まじぶっころしょ？
    俺はナイトではないがナイト弱体したらまわりが騒ぎだろうな
    俺はナイト弱体にはどちかというと大反対だな
    ナイト自体は強いがやっぱりナイトの性格のよさが武器だよなー憧れる
    弱体となえてる馬鹿のジョブがさっさと弱体されろよカス
only_one:
  title: 唯一ぬにの盾
  body: |-
    やっぱ騎士系は強いよな～圧倒的にさすがって感じ
    騎士の中で不安定だった竜も今回ので超つよくなったし暗黒騎士もスタン能力が光る機械が増えてきた
    まぁ一番光ってるのはやはりというかナイトだな
    ナイトと組めたらその日の狩りは成功したもも同然
    攻撃はヒキョウ者ではないから正正堂堂と避けないが現在失われし財産である盾を使って名実ともに唯一ぬにの盾
    しかも敵は攻撃を空蝉で避けられると「これはヒキョウ技なので仕方がない」と言う事になるが
    盾で受け流されるととてとての敵であるはずなのに潜在能力の桁違いの才能に「これほど才能があると勝てるわけがない」と諦め表情になる
    さらには最高の武器である片手剣Ａ+を所持し最高の武器から与えられるそのダメージ効率は最強その物
    さらにその武器受け流し能力はさすがＡ+といったところか敵に「そこにいたのにいなかった」という表情になる
back_world:
  title: 裏世界でひっそり幕を閉じる
  body: |-
    これ以上ナイトスレを立てるなよ
    ナイトはお前等のために盾をしてやってるんだからな
    ナイトが盾じゃなければすぐ死ぬくせに調子こき過ぎ
    あまり調子に乗ってると裏世界でひっそり幕を閉じる
til_three_budda:
  title: 仏の顔を三度まで
  body: |-
    普段は確かに心優しく言葉使いも良いナイトでも
    おまえらのあまりの粘着ぶりに完全な怒りとなった
    仏の顔を三度までという名セリフを知らないのかよ
apologize_immediately:
  title: はやくあやまっテ
  body: |-
    早く謝ってください！ナイトには攻撃きかない！
    僕は絶望的な戦いはしたくないです
    必死に逃げてもとんずらされて後ろから切られたくないです！はやくあやまっテ！！
understand:
  title: 今回のでそれがよくわかったよ
  body: |-
    やはりカイよりやはりソルだな・・
    今回のでそれが良くわかったよ>>199感謝
    まぁソルの聖騎士はまさしく鬼の力と言ったところかな
    火炎をまとってとぶさまはまさに最強の一文字につきるしかもついに念願のオーラの具現化が実現！
    オーラ爆発させる事によって手を出していないのにもかかわらず「お前そこにいたのか・・」と歩み寄るさまは敵に恐怖を与え敵は上にしか逃げる場所はないのだが
    ここもすでにボルカニックの射程内
    敵は画面端から逃げ出したそうにしてるが後ろがないので前門の虎前門の王神状態でなす術なしだしな
    はっきりいって200-202は情報に踊らされている可哀相な一般人
    あんな氷でできた剣で炎の剣に勝てるわけがない
    しかし腕力もみた感じソルが圧倒的に上で詩かも炎だから負ける要素ないので俺は199に賛成だな
everyone_pay_attension:
  title: みんながおれに注目する
  body: |-
    おれは光属性のリアルモンク属性だから一目置かれる存在
    たまに学校に行くとみんながおれに注目する
punching_machine:
  title: パンチングマシンで100とか普通に出すし
  body: |-
    ウザイなおまえケンカ売ってるのか？ボディブローとか言ってる時点で相手にならないことは証明されたな
    本当につよいやつは強さを口で説明したりはしないからな
    口で説明するくらいならおれは牙をむくだろうな
    おれパンチングマシンで１００とか普通に出すし
modesty:
  title: それほどでもない
  body: |-
    これが会話ログ
    俺＞こんにちはBurontさん
    Buront＞ 何か用かな？
    俺＞ ２ｃｈに書きましたか？
    Buront＞ 書いてない
    俺＞ そうですかありがとうグラットンすごいですね
    Buront＞それほどでもない
    やはり無実だった
    しかもグラットン持ってるのに謙虚にそれほどでもないと言った
modesty_res:
  title: それほどでもない_res
  body: |-
    >>91
    これが会話ログ
    俺＞こんにちはBurontさん
    Buront＞ 何か用かな？
    俺＞ ２ｃｈに書きましたか？
    Buront＞ 書いてない
    俺＞ そうですかありがとうグラットンすごいですね
    Buront＞それほどでもない
    やはり無実だった
    しかもグラットン持ってるのに謙虚にそれほどでもないと言った
modesty_res2:
  title: それほどでもない_res2
  body: |-
    それほどでもないが一級廃人として
    一般人から見ると憧れの的なんだろうな
    俺も謙虚だから「すごいですね」と尊敬されて誉められた時は
    それほどでもないと言う時もある
good_job:
  title: 見事な仕事
  body: |-
    >>95を見て笑ってる奴は何がおかしいんだ？
    ちゃんと無実を証明してログを公開しただけじゃん
    見事な仕事だと関心はするがどこもおかしくはない
real_monk_type:
  title: リアルではモンクタイプ
  body: |-
    何か勘違いしてないか？
    リアルでは俺は武器なんか持たなくても素手で怪力だから強い
    ＦＦではナイトだがリアルではモンクタイプだからな
diamond_marriage_ring:
  title: ﾀﾞｲﾔの結婚指輪のﾈｯｸﾚｽ
  body: |-
    たいがいにしろよｶｽが
    ﾏｼﾞで親のﾀﾞｲﾔの結婚指輪のﾈｯｸﾚｽを指にはめてぶん殴るぞ
    多分奥歯が揺れるくらいの威力はあるはずだしね
nutritive_food_in_hospital:
  title: 病院で栄養食を食べるハメになる
  body: |-
    なんだおまえら？ズタズタに引き裂いてやってもいいんだぞ
    あまり調子こくとリアルで痛い目を見て病院で栄養食を食べる事になる
retainer:
  title: 勝手に俺の家来になる
  body: |-
    少なくとも俺のところのＬＳではそれほど忍者に発言力は全くないかな
    忍者は性格が悪いのでムシしててたまに話しかけてやると勝手に俺の家来になる
lifespan_mach:
  title: 寿命がストレスでﾏｯﾊ
  body: |-
    別に俺はｻﾎﾟにはこだわらないし楽しければ良い
    空蝉対策とかすこし頭を使えばどうでもなる問題を考えもせず人に頼り切るから
    頭も腕も落ちたｼﾞｮﾌﾞとしては最強、腕は半人前という終わってる状態になるんだろうな
    正直お前らのいちゃもんつけにはﾑｶﾑｶしてるから黙ってｽﾚ落してくれるか？
    このままでは俺の寿命がストレスでﾏｯﾊなんだが・・
siily_fooly:
  title: 浅はかさは愚かしい
  body: |-
    またageてやがる
    メール欄に何か入れてればageを見破れないとでも思った浅はかさは愚かしい
nine_enough:
  title: ９枚で良い
  body: |-
    そういえばうちのＬＳの詩人がﾅｲﾄを好きみたいだぞ？
    ダボイでトカゲを狩っていたらリンクして逃げているときにすれ違っただけのナイトが助けてくれたらしい
    黄色いトカゲにディアガとばしたら敵が猛威を振るってきた
    ところがトカゲの攻撃は圧倒的な戦力を持ったﾅｲﾄに対してあまりにも無力過ぎた
    高位ケアルをほどこしてやると狂ったようにトカゲが牙を剥いて来たらしいが次々と倒されていく仲間のトカゲを見て絶望しながら消えていったらしい
    詩人はそこで溜めてたトカゲの皮を１Ｄトレードしたが９枚で良いといわれたらしい
    今のＬＳではそのﾅｲﾄは謙虚なﾅｲﾄで人気者
knight_rank:
  title: さすがにナイトは格が違った
  body: |-
    ＬＳのナイトがこのＬＳでは俺はおさまらぬだろうとＬＳを抜けると言い出した
    リーダーは言った「たしかに抜けるのは勝手だがそれなりの抜け方があるでしょう？」といったが残念ながら引き止めたいのがﾊﾞﾚﾊﾞﾚで
    ＬＳ人は「ナイトさんが抜けるならわたしも抜ける」「ナイトがいないＬＳに未来はにい」「お手本がいなくなる・・」
    ナイトはどこでも引張りたこでつい先日もＨＮＭＬＳに勧誘されていた
    リーダーに「何か言う事はないか？」というとリーダーはテルで「もう残る気はないのか？；」と言ってきたが俺は「おいィ？お前らは今の言葉聞こえたか？」といったら
    「聞こえてない」「何か言ったの？」「俺のログには何もないな」という返事
    等々リーダーの口から「残ってください；；」とリーダーなのに格の違いを見せつけられ自分の地位を悟ったのかいつのまにやら丁寧語になっていた
    ナイトは「地位と権力にしがみついた結果がこれ一足早く言うべきだったな？お前調子ぶっこき過ぎてた結果だよ？」
    リーダーはＬＳを壊さないでと泣いてきたがナイトに未練は無かったナイトはパールを投げ捨てた
    仲間達は「存在があまりに大き過ぎた」「これじゃ何も出来ない」系の事を言っていたがもうだめ
knight_rank_res:
  title: さすがにナイトは格が違った_res
  body: |-
    もしかしたら同じＬＳかもなやはりナイトは中心人物でそれを妬んだリーダーがいると分解してしまう
    ナイトは影の存在でも構わないのだが勝手に存在が目立ってしまう
    それに見合った報酬が必要なのにりーだーがケチで何もやらなかった結果がこういう結果をもたらした
    ちなみに俺は赤でこのナイトの支持者
    このＬＳはもうだめかな中心人物でヌードメーカーが不在では持つわけもないが
    いまごろはＨＮＭと第一戦で戦ってるらしい
kanaguri_sutennzo?:
  title: ﾏｼﾞでかなぐり捨てﾝぞ？
  body: |-
    お前ら勝手に名前晒されてる奴の気持ち考えたことありますか？
    ﾏｼﾞでぶん殴りたくなるほどむかつくんで
    止めてもらえませんかねえ・・？
    事前に晒されるとわかっていれば反抗も出来ますが
    わからない場合手の打ち様が遅れるんですわ？お？
    人の意見に流される糞ばかりなので本人の意見が遅れると捏造で好き放題叩かれまくられてﾏｼﾞで殺す。
    ちょとｓＹレならんしょこれは・・？晒すなら本人に断ってやれよ。
    これからはそれが出来ないやつが悪者でＦＡ！それくらいも出来ない卑怯者はﾏｼﾞでかなぐり捨てﾝぞ？
stop_stupid:
  title: おい、やめろ馬鹿
  body: |-
    おい、やめろ馬鹿
    このスレは早くも終了ですね
huuinn_ga_tokerareta:
  title: 封印が解けられた！
  body: |-
    俺は結構攻撃的なジョブをいくつも持ってるのだが
    メリポはナイト暗黒シーフ白詩人ＸでいくがＸはＬＳに居ない時で野良で誘うんだが
    だいたい最初はシーフ見た瞬間「こんなＰＴで稼げるわけがない・・」とあきらめが鬼なった
    俺はＬＳでシーフに「今回あきらめ顔になってるので全力出しても良いぞ」というと
    「やっと許しが出たか！」「封印がとけられた！」と仲間がもじもじしだしたので急に入ったメンバーは何が起きようとしてるのか謎みたいだった
    戦闘に入ると忍者とかとは別次元のナイトが最強の挑発の持ち主なので後衛にタゲが行く事はないので後衛も本気の力が出せる
    するとつぎは攻撃の番なのだが暗黒の最強Ｄ値の鎌と最強の盾能力でありながら攻撃も一流のナイト（攻撃力も一流なのがタゲ取り能力もさされてる）
    さらにシーフがいる事によって釣りがスムーズに行きヘイトの低い後衛に騙しをガンガンいれると敵は「なんで後衛がこんな攻撃力を持っているんだ」と絶望になる
    しかもおもわず命乞い寸前だったのか手持ちのお宝を置いていく・・命乞いが成立する前に攻撃力で倒してしまうんだが野良のやつはたいていこれでこのメンバーを必然的に抑えてくるよな
same_era:
  title: 同じ時代を生きただけのことはあるなー
  body: |-
    あのころはバランス壊してるジョブがなくて良かったと俺は思うな
    あのころからいまでも良いと思うのはやっぱり、ナイトだなぁ
    俺はナイトとか、育てて無いが今もだがナイトに誘われるとレベルが上がると身震いしてしまう
    あのころの敵は強くて今の忍者とか、雑魚にしか勝てないからわからないだろうがやっぱり盾はナイトだけだなと今でも思う
    ナイトにはあのころの敵があってたな、ナイトは強過ぎる敵仕様なので今の弱い敵では力が出せない
same_era_res:
  title: 同じ時代を生きただけのことはあるなー_res
  body: |-
    >>76
    同じ時代を生きただけの事はあるなー
    今でも１ＰＴ１ナイト時代は最高の思い出になっているんが今のＰＴはかわいそうだな、なぜならば本当の緊張感が味わえない
    今のは何とは言わないが卑怯な雑魚盾でとてとてとは名ばかりの雑魚敵を倒しているだけ
    はっきりいってとてとてじゃない、あれは強いレベルだと思った
    ところがもかしの敵は強い表示だったけどとてとてクラスの敵ばかりだった
    盾以外のジョブがタゲ取るとすぐに死んでしまうのでナイトは剣や盾と共に光り輝いていた
    それがいまでは雑魚にでも卑怯ワザを使わないと倒せないになってしまっている
    はっきりいってＰスキルレベル下がり過ぎだと思うんだがなぁ、俺は別に良いけど
knight_does_not_select_job:
  title: ナイトはジョブを選ばない
  body: |-
    >>79
    俺は白なんだがナシのセットは最強だと思った
    ＰＴを俺が作っていたんだが盾はナイト以外に考えられなかったのでナイトを誘ったんだがナイトを取られたと思ったんだろうな
    黒が二人俺に「ナイト様誘いました？」と言ってきた
    俺はハイエナが二匹も同じジョブを狙っていたと冷や汗をかきながらナイトに選ばれた興奮に身を震わせた
    黒達には「誘いましたが、入りたいですか？」と心の広大さをアピールできて気持ち良かったなぁ・・・（ナイトはジョブを選ばない）
    ＰＴ会話で「＠２はどいつらがいいですか？」と聞くとナイトが「シーフが良いかも知れない」とＰＴへ来てもらったのに他とは違って意見もしっかりするリーダーシップを取ってた
knight_does_not_select_job_res:
  title: ナイトはジョブを選ばない_res
  body: |-
    狩場に着くとナイトポップを待ち切れなかった雑魚どもが死にまくっていた
    生き残っているＰＴもタゲがフラフラで回復役の白が逃げながらしんでいって白を失ったメンバーは諦めた様に次々と死んでいってた
    その中で忍者だったかな・・・一人だけ微塵でロスト免れてたんだが俺はその時から忍者の汚さが目についていた
    かまわずに狩りをしようとすると腕の良いシーフが言われる前に自主的に釣りに行ってて好印象だった
    しかもナイトとシーフの腕がよくＰＴも明るく楽しくなってきたんだが
    黒が調子のって大出力の魔法で一瞬タゲがふらつきそうになったがさすがナイトだった
    一瞬でタゲを安定させ「もっと本気でいいぞ」と言っていたシーフも「だまし討ちで最強タゲ確保」というと常時インビンなみの高ヘイトをだしていた
    黒達は「今まで魔法を抑えて来てた」「本気を出せない辛いレベル上げだった」と感謝の言葉が思わず出ていた・・・
ky_user_zako:
  title: カイを使うやつは雑魚狩り専門
  body: |-
    遊んでいたんだがカイで１０連勝とかしてるやつがいたんで見ていたら１０連勝の相手は小学生くらいの子供だった
    俺は「恥かしくないのか」ときくと聞こえないフリしていきなり飛ぶながら叩きつけるワザ使っていたが
    子供は１回攻撃無視のワザを使っていて無残に返り討ち食らっていた
    子供は「何故？」と苦笑しながらダウンしてるカイに近付きおきぜめを狙っていたんだがカイは卑怯にも無敵の昇竜拳を使っていた
    だが子供はそれを読んでたみたいで防御してた絶望しひややせかきながら無残に落下してくるカイにバスター（最強攻撃）を食らわせてた
    カイ使いは「今の離れてただろ・・」と一人ごと言っていたが誰も聞いてなかった
    卑怯にもきょりがあいたので氷だして削っていたんだがぽちょきんも飛び跳ねて頑張っていたらギャラリーが集まってきてたんだがその攻めが恥かしくなったんだろうな
    急に「そろそろかな」といって攻撃的になって空中から攻めて行ったらそこにあったポチョムキンの腕で捕まってた
    俺は「お前まさか…」というと顔真っ赤にしながら「今の飛んでないんだが・・」とレバーにグルグルまわしてた
    そのかいあってか残念な事に強力な追加攻撃はミスしてたみたいだが安心して落下してきたカイにまたおき攻めで攻め掛かり蹴りをガードさせた直後のバスター（最強攻撃）で止めを刺されていた
    青くなってるカイ使いに「お前誰に勝ったの？」と聞くと奥のほうでメダルゲームしてる子供を指したしかも「呼んで来て…」と頼んできたがアワレで仕方が無かった
evidence:
  title: 俺がどうやって○○だって証拠だよ
  body: |-
    >>10
    俺がどうやってBurontだって証拠だよ
    言っとくけど俺はBurontじゃないから
    あんまりしつこいとバラバラに引き裂くぞ
gratton_saikyou:
  title: グラットンソードは最強
  body: |-
    グラットン有り：Ｐスキル高い・性格良し・会話も楽しい
    グラットン無し：Ｐスキル低い・厨房率高い・面白味の無い奴
gratton_saikyou_res:
  title: グラットンソードは最強_res
  body: |-
    >>11
    言っておくけど俺は既にグラットン持ってる
    これ手に入れてからはうらやましがられて尊敬されてる
    ＬＳでも発言権強くなり、俺にまともに口答えできる奴いなくなった
gratton_saikyou_res2:
  title: グラットンソードは最強_res2
  body: |-
    やはりグラットン持ってないと駄目か
    俺もがんばって手に入れようと思ってるがなかなか大変だぜ
    一級廃人の証っていうだけの事はあるよな
    持ってる人憧れちゃうなー
i_think:
  title: 俺が思うに
  body: |-
    >>102
    俺が思うに全員別人なのではないか？
    IDはたまたま同じになる事が結構あるらしい
i_think_res:
  title: 俺が思うに_res
  body: |-
    おまえら素人だなＩＤはまれによく同じＩＤになったりする
    ズタズタにされたいのか？調子こいてるとリアルで痛い目に会う事になるから注意すべき
i_think_res2:
  title: 俺が思うに_res2
  body: |-
    俺が思うに偶然IDが一緒になった人だと思うな
    こういう人気のあるところは通信回線が混乱してたまに良くあるらしいぞ俺じゃない
guratton_swift:
  title: グラットンスウィフト
  body: |-
    >>183
    まともに討論してるところにゴミが現れたか
    グラットンスウィフトでバラバラに引き裂いてやろうか？
real_story:
  title: (リアル話)
  body: |-
    とてとて戦の再開
    瞬間テルが殺到した
    どうやらナイトの力が必要らしい
    面倒だったので断ったが粘着されたので
    仕方ないから参入して稼がせてやった
    ヒュムリア♀とエルリア♀からフレンド登録の要請が来た
    ナイトは最強だと思った（リアル話）
real_story_res:
  title: (リアル話)_res
  body: |-
    俺がログインするたびにその仔猫（リア♀）たちが戯れてくる
    仕方ないからＰＴに入る
    どうやら俺を崇拝しているらしい
    ＰＴに入ってないときにもTellしてくる
    ナイトならではの出来事（リアル話）
real_story_res2:
  title: (リアル話)_res2
  body: |-
    おれは顔真っ赤になんてしていない（リアル話）
    おまえらの嫉妬は見苦しい
    人をバカにする暇があるなら自分を磨け
    今のおれはそう言うふうにしてある
    もてる秘訣はここにあるのかも（謙虚）
real_story_res3:
  title: (リアル話)_res3
  body: |-
    お前その言葉使ってると逮捕だぞ
    以後気をつけろ（この辺の心配りが人気の秘訣）
dedeo_4_men:
  title: ででお四天王
  body: |-
    そろそろ明かそうと思ってたがやはり気づく奴もいたか
    俺は実はででお四天王の一人
    前におまえらがこういったくだらん騒ぎをした時
    食い止めた実績があるのだよ
dedeo_4_men_res:
  title: ででお四天王_res
  body: |-
    どうやってそれが反省してないという証拠だよ？
    もし全く反省してないなら血も涙もなくなんとも
    思ってないと言う事だから記事にも書かないでしょう
    あの記事はででおさんが心に気にしてるから反省の意味として書いたと取るべき
vana_than_real:
  title: リアル世界よりも充実したヴァナ生活が認可される
  body: |-
    圧倒的な生命維持能力を保持するナイトと赤の組み合わせは獣使いじゃないにに巣も他の者をを魅了するほど
    何度も見つめられ装備の貴重さを世に広めることでリアル世界よりも充実したヴァナ生活が認可される
vana_than_real_res:
  title: リアル世界よりも充実したヴァナ生活が認可される_res
  body: |-
    ♀は強い男に憧れるから最強の伝説武具装備してるのはもてる
    最強の武具装備してると全身からかもし出すエネルギー量がオーラとして
    見えそうになる
three_continuous:
  title: ３回連続見つめられた
  body: |-
    23 名前：既にその名前は使われています 投稿日：03/10/30 13:01 QcBxXqoc
    ロンフォでウサギNMを待つ間に生半可なナイトでは使えないホーリを使って敵を掃除していたら３回連続見つめられたから
    「抵レベル体では見たことの無いものだから覗きたかったのもわかるが魔法であって武具は無関係」
    と伝えてやったがむ反応たぶん信用してない
    信用してないところでジュノ競売でベヒーモスマントの値段を見たらあきらめることになる
real_pain1:
  title: リアルで痛い目1
  body: |-
    27 名前：既にその名前は使われています 投稿日：03/10/30 13:09 QcBxXqoc
    過去少し間違ったくらいで粘着ウザイな
    ベーモスマントと言うものは存在していないことがわかった
    これでいいか以降揚げ足取りは禁止
    揚げ足取った奴はリアルで痛い目を見ることになる
real_pain2:
  title: リアルで痛い目2
  body: |-
    36 名前：既にその名前は使われています 投稿日：03/10/30 13:22 QcBxXqoc
    リアルで痛い目を見たいのかおれはリアルでモンク属性だから相当の力持ち
real_pain3:
  title: リアルで痛い目3
  body: |-
    39 名前：既にその名前は使われています 投稿日：03/10/30 13:29 QcBxXqoc
    いい加減にしろよ実名出すのは犯罪だぞ!!
    お前ら警察に逮捕されることになるリアル犯罪者
real_pain4:
  title: リアルで痛い目4
  body: |-
    42 名前：既にその名前は使われています 投稿日：03/10/30 13:32 QcBxXqoc
    ボコボコにされたいらしいなさっきも言ったがおれはリアルモンク属性だから手加減できないし最悪の場合病院に行くことになる
everyone_attention_me:
  title: みんながおれに注目する
  body: |-
    67 名前：既にその名前は使われています 投稿日：03/10/30 14:45 QcBxXqoc
    おれは光属性のリアルモンク属性だから一目置かれる存在
    たまに学校に行くとみんながおれに注目する
nightmare_sword:
  title: ナイトメアソードの使い手
  body: |-
    131 名前：既にその名前は使われています 投稿日：04/03/04 15:11 zQEGPbgw
    しかもナイトメアソード所持者はいずれも鯖で有数の超ナイト
    ・一級の使い手→大手LSから接待→HNM→凄まじい武器の入手→PTでの効率アップ→武器防具の話を聞かれる→人気者
    ・普通の使い手→重要な戦闘で信頼を得られない→庶民武器→効率悪い→何も話を聞かれない無言PT→雑魚
god_and_hell1:
  title: 神の贈物と地獄の宴1
  body: |-
    139 名前：既にその名前は使われています 投稿日：04/03/04 15:33 zQEGPbgw
    調子にのるなよ本気出すぞ？
    リアル格闘フレと俺はかなりの戦闘力持ってるから調子に乗ってるとまずい事になる
    俺は学校でもかなり注目されてたしなリアル格闘フレも別学校だがやはり注目度はかなりの高さらしい
    ここでしか強気に出れない奴はﾏｼﾞでｳｻﾞｲなﾏｼﾞでぶっ飛ばしてやるから鯖とネームいってみろよ
god_and_hell2:
  title: 神の贈物と地獄の宴2
  body: |-
    144 名前：既にその名前は使われています 投稿日：04/03/04 15:46 zQEGPbgw
    ほらな？やっぱりお前ら俺が怖くて鯖と名前言えないんだ
    な 俺は逃げも隠れもしてない
    お前ら覚えてろよ？PvP機能は俺にとっては神の贈物だがお前等にとっては地獄の宴だからな
    せいぜい裏世界で後ろに怯えながら遊ぶんだな
    リアルで俺が怖くないなら鯖と名前あかしてみろよ雑魚！出来ないんなら俺の勝ち
reverse_world1:
  title: 裏世界でひっそり幕を閉じる
  body: |-
    11 名前：既にその名前は使われています 投稿日：04/03/03 15:24 4Ei9AWRA
    これ以上ナイトスレを立てるなよ
    ナイトはお前等のために盾をしてやってるんだからな
    ナイトが盾じゃなければすぐ死ぬくせに調子こき過ぎ
    あまり調子に乗ってると裏世界でひっそり幕を閉じる
reverse_world2:
  title: 裏世界でひっそり幕を閉じる
  body: |-
    16 名前：既にその名前は使われています 投稿日：04/03/03 15:34 4Ei9AWRA
    うざいやつがいるな
    たまに実名を出すやつがいるがそれは犯罪だぞ！
    名前出す奴は国家戦力を舐めすぎ
    お前の家の住所ぐらいはすぐにばれる
hurry_apologize1:
  title: はやくあやまっテ！！1
  body: |-
    51 名前：既にその名前は使われています 投稿日：04/03/03 17:02 4Ei9AWRA
    こんな恐ろしいい敵を作りたくないので僕はあやまりますごめんなさい
    他の人も早く謝るべき死にたくないなら謝るべき
    ごめんなさい経験値ロストしたくないんです
hurry_apologize2:
  title: はやくあやまっテ！！2
  body: |-
    52 名前：既にその名前は使われています 投稿日：04/03/03 17:03 4Ei9AWRA
    >>51
    ほうお前はなかなか解っている様だな
    命は助けてやる俺は優しいからな他のやつらにも伝えてやるべき
hurry_apologize3:
  title: はやくあやまっテ！！3
  body: |-
    54 名前：既にその名前は使われています 投稿日：04/03/03 17:06 4Ei9AWRA
    hai!!他の人も早く謝ってください！
    まだ僕は死にたくないんです！！経験値ロストが怖いんです！
    僕の頑張った時間を奪わないで下さい！僕がロストしたらここで謝らなかった人達のせいですね？
hurry_apologize4:
  title: はやくあやまっテ！！4
  body: |-
    55 名前：既にその名前は使われています 投稿日：04/03/03 17:08 4Ei9AWRA
    >>53
    上げるな雑魚お前は俺が怖いのに必死につよがってもだめ
    ビビってるのばれてるからな
    怖くないなら鯖言ってみろよ雑魚
hurry_apologize5:
  title: はやくあやまっテ！！5
  body: |-
    59 名前：既にその名前は使われています 投稿日：04/03/03 17:14 4Ei9AWRA
    まだあげてる雑魚がいるなふざけるなよ
    お前はどこにも逃げられないプレシャーを背負う事になった
    後ろに気をつけておくことをお進めする不意だまでお前の命は非常にまずい事になる
hurry_apologize6:
  title: はやくあやまっテ！！6
  body: |-
    63 名前：既にその名前は使われています 投稿日：04/03/03 17:17 4Ei9AWRA
    早く謝ってください！ナイトには攻撃きかない！
    僕は絶望的な戦いはしたくないです
    必死に逃げてもとんずらされて後ろから切られたくないです！はやくあやまっテ！！
hurry_apologize7:
  title: はやくあやまっテ！！7
  body: |-
    69 名前：既にその名前は使われています 投稿日：04/03/03 17:24 4Ei9AWRA
    ここであげたやつら全員後ろからの不意だまに気をつけるべき
    もうどこにも逃げられない
    いまはレベル上限が７５になってテレポも出来る始末
    どこに行ってもとんずらー不意だまからは逃げられない
    リアルでは臆病者のくせにゲームでだけは強気になったのが命取り
