ls_reliability:
  title: ナイトと忍者のＬＳ信頼度は違いすぎた
  body: |-
    やはり忍者よりナイトの方が頼りにされていた
    キングベヒーもスとの戦いでおれは集合時間に遅れてしまったんだがちょうどわきはじめたみたいでなんとか耐えているみたいだった
    おれはジュノにいたので急いだ
    ところがアワレにも忍者がくずれそうになっているっぽいのがＬＳ会話で叫んでいた
    どうやら忍者がたよりないらしく「はやくきて～はやくきて～」と泣き叫んでいるＬＳメンバーのために俺はとんずらを使って普通ならまだ付かない時間できょうきょ参戦すると
    「もうついたのか！」「はやい！」「きた！盾きた！」「メイン盾きた！」「これで勝つる！」と大歓迎状態だった
    忍者はアワレにも盾の役目を果たせず死んでいた
    近くですばやくフラッシュを使い盾をした
    忍者から裏テルで「勝ったと思うなよ・・・」ときたがＬＳメンバーがどっちの見方だかは一瞬でわからないみたいだった
    「もう勝負ついてるから」というと黙ったので戦士サポ忍の後ろに回り不意だまスフィストを打つと何回かしてたらキングベヒんもスは倒された
    「ナイトのおかげだ」「助かった、終わったと思ったよ」と忍者を行き帰らせるのも忘れてメンバーがおれのまわりに集まってきた忘れられてる忍者がかわいそうだった
    普通なら裏テルのことで無視する人がぜいいんだろうがおれは無視できなかった
    みんなとよｒこびほめられたかったのでレイズを唱えてやったらそうとう自分の裏テルが恥ずかしかったのかＨＰに帰って行った
aeris:
  title: エアリスを使うやつは心が醜い
  body: |-
    俺はＦＦ通してやってる自他共に認める熟練者なのだが先日ゲームに無関心だった姉が急にＦＦ７を貸してくれと言って来た
    俺はどうせＦＦ７のキャラ目当てだなと踏んでいたんだがどうやらその通りみたいで、腐女子仲間に何を思ったかＦＦ７ＡＣを借りて見たらしい
    そういうの嫌いだから俺は｢いや、そういうのでやって欲しくないから｣と言ったら何か必死な顔して出て行った
    そしたらムキになってなんか中古で買ってきたみたいで１人でむくむくとやっていた
    しばらくは俺も放置していたんだが何かたまたまのぞいて見るとクラウド・レッドⅩⅢ・エアリスとか貧弱ＰＴでもう見てられなかったから
    ｢何でエアリス使ってんの？ティファのが強いしエアリス死ぬよ？｣ってやさしく忠告してやったらなんか顔真っ赤にしてコッチにらんで来た
    俺は｢何？｣って言ったらすごい形相で｢クラエアがデフォだしティファとかブサイクで醜い女入れたくない｣とか怒鳴ってきた
    そこまで俺はティファは好きではなくむしろ強キャラでモンクタイプが好きだったから言っただけなのになんかカチンときので
    ｢は？エアリスってリミットゴミでしょ？それに強制離脱するから育てても無駄｣と正論言ってやったら今にも俺を殺してきそうな殺意を向けてきた
    実際俺は不良界でも結構有名でケンカとかでもたいしてビビる事はまず無かったが生まれて初めてほんの少しビビった
    そしたらなんか｢あたしの勝手じゃん！クラエア馬鹿にする気？そうならあんたもう死ね！｣とか実の弟の俺にリアルで殺意向けてヤバかった
shameless_ky:
  title: 恥知らずなカイ使いがいた！
  body: |-
    俺はソルを使い手なんだが相手が残念な事にカイを使ってきたので「お前それで良いのか？」と言うと「何いきなり話かけて来てるわけ？」と言われた。
    俺の弟がカイの熟練者なのだがおれはいつも勝つから相手が気の毒になったので聞いただけなんだがむかついたので「お前ﾊｲｽﾗでﾎﾞｺるわ・・」と
    言って開始直後に力を溜めて前ﾊｲｽﾗしたら多分リアルでビビったんだろうな、、ｶﾞｰﾄﾞ固めてたからｷｬﾝｾﾙしてｶｶッっとﾀﾞｯｼｭしながらﾊｲｽﾗしたらかなり青ざめてた
    おれは一気に空中にとんだんだけどカイが硬直してておれの動きを見失ったのか動いてなかったからｺﾏﾝﾄﾞ投げでｶﾞｰﾄﾞを崩した上についげきのグランドヴァイパでさらにﾀﾞﾒｰｼﾞは加速した。
    わざと距離をとり「俺はこのままﾀｲﾑｱｯﾌﾟでもいいんだが？」というとようやく必死な顔してなんか剣のはしっこから氷出してきた。
    おれはしゃがみダストで回避、これは一歩間違えるとｶｳﾝﾀｰで大ﾀﾞﾒｰｼﾞを受ける隠し技なので後ろのギャラリーが拍手し出した。
    俺は「うるさい、気が散る。一瞬の油断が命取り」というとｷﾞｬﾗﾘｰは黙った
    カイは必死にやってくるが、時既に時間切れ、下段ｶﾞｰﾄﾞを固めた俺にｽｷはなかった
    たまに来る下段ｶﾞｰﾄﾞでは防げない攻撃もキックで撃退、終わる頃にはズタズタにされた金髪の雑魚がいた
    「いつでもﾊｲｽﾗでトドメは刺せた、あの時氷だそうとしたときにも実はズタズタに出来た、」とかいった
    そしたら「いや今のハメでしょ？俺のシマじゃ今のノーカンだから」とかいったので俺がヒト睨みするとまた俺から視線を外した、２戦目は俺のﾊｲｽﾗを先読みしてたみたいでいきなりバックステッポで回避された
    「ほう、経験が生きたな」と少し誉めるとｼﾞｭｰｽをおごってくれると言う約束をしたので空中でダストを当てて一気にかけよりダストと足払いの二択を迫り
    ５回くらい足払いしたら死を感じたのかｶﾞｰﾄﾞしようとしたので近づいてﾊｲｽﾗ投げをお見舞いしてやった、絶望でダウンしているところにｷﾞﾛﾁﾝのﾊｲｽﾗがダブルで入れた。
    「今のがリアルでなくて良かったな、リアルだったらお前はもう死んでるぞ」というと想像して圧倒されたのか動きが鈍くなったのでガンフレで動きをコントロールしさらに時間までコントロールしていることにも気付かせずにﾀｲﾑｱｯﾌﾟさせた。
    そしたら「まただよ（笑）」とか負けたくせに言いワケ言ってたから「限られたルールの中で勝利条件を満たしただけ」といったら顔真っ赤にして３戦目はけっこう攻撃的だったけど挑発に軽々と乗ってくる馬鹿には確実な死が待っていた。
    ハイスラの恐怖が完全に摺り込まれている為思うように近づけないでいるようで空中来たらキックでけん制し飛び込んできたら前ハイスラでいつの間にかｶﾞｰﾄﾞｹﾞｰｼﾞは光っていたから「グランドヴァイパでトドメさすよ」と言うとカイは必死にｶﾞｰﾄﾞしたから
    狙い通り３段目くらいをロマキャンすると予想通り青ざめてｶﾞｰﾄﾞしてたから投げで強打したのちハイスラでトドメ。
    あとはﾀｲﾑｱｯﾌﾟまで粘った。俺の下段ｶﾞｰﾄﾞは固く、隙を見せなかった。カイも下段ｶﾞｰﾄﾞできない攻撃してきたけど反撃もここまで。残念ながら前半の遅れを取り戻す事が出来なかった。
    その後ボコボコにして圧勝してやった
    変な空間になったので俺はミステリーを残す為勝ちの画面になったと同時に家に帰ったが多分不良界で伝説になってる
dirty_ninja:
  title: 汚いなさすが忍者きたない
  body: |-
    これ立てたの絶対忍者だろ･･汚いなさすが忍者きたない
    俺はこれで忍者きらいになったなあもりにもひきょう過ぎるでしょう？
    俺は中立の立場で見てきたけどやはりナイト中心で行った方が良い事が判明した
    忍はウソついてまでＰＴの盾役を確保したいらしいがナイトに相手されてない事くらいいい加減気づけよ
    ナイトは忍者よりも高みにいるからお前らのイタズラにも笑顔だったがいい加減にしろよ
golden_iron:
  title: 黄金の鉄の塊
  body: |-
    お前らは馬鹿すぐる
    ナイトが強いのは当然に決まっている
    黄金の鉄の塊で出来ているナイトが皮装備のｼﾞｮﾌﾞに遅れをとるはずは無い
    確実にナイトはエクスカリバを手に入れたら高確率で一番最強になる
mad_and_die:
  title: 頭がおかしくなって死ぬ
  body: |-
    もうここまででも十分にグラットンの勝ちは圧勝に決まったのだが
    さらに攻撃は続く
    次は見た目に注目するのだが
    セイブはただのひょろっとした弱そうな形
    あれで斬られてもあまり痛くはない
    しかしグラットンは尖った部分が多くあの部分でさらに敵に致命的な致命傷を与えられる
    色も黒っぽいのでダークパワーが宿ってそうで強い
    ちなみにダークパワーっぽいのはナイトが持つと
    光と闇が両方そなわり最強に見える
    暗黒が持つと逆に頭がおかしくなって死ぬ
lightning_left:
  title: 雷属性の左
  body: |-
    俺はしがないエリート会社員なんだが先週同僚のもてない♂がなれなれしくも話しかけてきてウザかったが
    まぁ聞いてやるかと思って聞いてやったら何やら合コンをセッテングしてほしい様子で面倒だったんだがやってやった
    俺の行きつけの子じゃれたＢＡＲに行ったんだが暫らく皆で良い感じで話してたらよそで言い争いがはじまった
    せっかくのふいんきが台無しになって俺が主導権にぎって進めてたが仕方ないと思い店換えをする事にしたが
    何やらリアルファイトに発展したようで店員もビビりまくっているようだった。誰かが｢通報・・｣と言ったので俺らはほっといて出るつもりだったんだけど
    いきなり飛んできたビールが俺目当てのいけてる♀に直撃→俺の怒り発動の連鎖で俺は現場に躍り出ると
    いかついオッサンが｢何だガキ？ひっこんでろ！｣と言って来たので｢おい・・ツレにビールかかったんだわ・・クリ代払ってもらおうか？｣
    と怒りをこめて言い放つと｢言っとくが俺は空手二段だ。そこに転がってる奴みたくなりたくなかったらうせろ｣と息巻いてきたので
    スキだらけだったので雷属性の左をジョーにヒットさせてやって｢口で語るひまがあるなら手を出すべきだったな｣と言ってＫＯした
    自称空手二段は何がおこったのか分からずブザマにもプルプル足震えて倒れた
    おれはソイツからクリ代と飲み代を取りすかさず店に払って♀達を送って帰った。ちなみに警察はだいぶ後に来たらしい
    その後は一緒にいた♀達にどうやらほれられてしまい対応に困ったんだが何しに行ったか分からなかった同僚♂がアワレだった
    嫌味かは知らないが｢良いなケンカ強くて頭が切れる人は・・｣とかかわいそうな事言ってきたが俺は｢男ならアレくらいチョロイ事｣
    と大人の対応をしてやるとよほど悔しかったのか今さらながらスポーツジムで体を鍛えだしていた
rage:
  title: 俺の怒りが有頂天
  body: |-
    お前らは一級廃人のおれの足元にも及ばない貧弱一般人
    その一般人どもが一級廃人のおれに対してナメタ言葉を使うことでおれの怒りが有頂天になった
    この怒りはしばらくおさまる事を知らない